### PR TITLE
Fixed # issues with rewrite rules

### PR DESCRIPTION
**Pull request by foliovision**

### CODE REVIEW

**Comment by foliovision** [comment]
We need this fix as we use # in some custom post type permalinks - we pass the element ID in the URL so that opening our custom post scrolls to the right place.

**Comment by torounit** [comment]
Sorry, I do not merge your fix. 
It should be made in the template side.

**Comment by foliovision** [comment]
We put it into your rewrite module, as otherwise PHP shows error when it executes the regex matching on the rewrite rule. 

You see, if there is # in the rewrite rule: out-page#our-anchor

WordPress then checks the regex like this:

#out-page#our-anchor#

And that triggers the PHP warning. That's why we put it into the rewrite module. What do you mean it should be in template? Please explain.

**Comment by foliovision** [comment]
Are there any news on this?

**Comment by foliovision** [comment]
I see verion 1.5.2 is out but it doesn't seem it fixed the issue. Seems like you added a way of putting in custom modules, although it's not mentioned in the changelog.

**Comment by torounit** [comment]
That's right.

Sorry , but it is not yet able to update the change history . To update in the near future .

#51

**Pull request closed without merging**
